### ISSUE TITLE
Draf Mainnet Network Launch Steps

### ISSUE THREAD

**Issue by mnaamani** [Joystream/joystream#4474]
### Network Launch Steps

Assumption - infrastructure nodes are already setup:
9 validators (first used as build node)
5 boot nodes
3 rpc/qn nodes

#### Ensure DNS records for boot and rpc nodes is correct:
- mainnet-rpc-1.joystream.org, mainnet-rpc-2.joystream.org, ..., mainnet-rpc-N.joystream.org
- mainnet-boot-1.joystream.org, ...  , mainnet-boot-N.joystream.org

#### 'Inputs' should be available
 (provided by martin):
- `members.json` file (needed for avatar migration)
- `initial-balances.json` file (needed for chainspec)
- `sudo` Address
- Initial authorities `stash` and `controller` accounts.

#### Avatar Migration
- Deploy new Avatar service or use production  at `https://atlas-services.joystream.org/avatars/` (coordinate with atlas team to make sure it is not purged)
- backup avatar service storage dir
- Use [avatar migration tool](https://github.com/mnaamani/avatar-migration) to produce final members.json for member bootstrapping. -> share with martin.

##### Create/Obtain the `inventory`, install ansible-galaxy requirements..
`ansible-galaxy install -r devops/ansible/requirements.yml`

##### prepare network `config.yml` from template below:
```yaml
data_path: /path/to/mainnet/
# accounts and balances
initial_balances_file: /path/to/mainnet/initial-balances.json
sudo_account: "j4SudoAddress..."
authority_stash_and_controller_accounts: [
  "j4StashAccount1,j4ControllerAccount1",
   "j4StashAccount2,j4ControllerAccount2",
   .....
  "j4StashAccount9,j4ControllerAccount9"
]
chainspec_creation_strategy: new-with-authority-accounts
deployment_type: live
network_id: joy_mainnet
network_name: "Joystream"

# Build
git_repo: https://github.com/joystream/joystream.git
branch_name: "mainnet" # or ` master` if mainnet was merged to master
runtime_profile: "" # empty string = production

# Relative to ansible_user home dir.. 
remote_data_path: artifacts
remote_code_path: joystream

use_local_chain_config: false
```

#### Make nodes ready for (re-)/deployment
Below steps are destructive! Take care that you know what your are intending to do.
Wiping keystore will produce new validator session keys and therefore a new genesis block.

##### Check all nodes are reachable
```sh
ansible all -i ./inventory -m ping
```

##### Stop current chain
Stop joystream-node on all machines and remove systemd service file.

```sh
ansible all -i ./inventory --become -a "systemctl stop joystream-node"
ansible all -i ./inventory --become -a "rm /etc/systemd/system/joystream-node.service"
ansible all -i ./inventory --become -a "systemctl daemon-reload"
```

##### Delete pre-built binaries

```sh
ansible all -i ./inventory -a "rm -fr bin/"
```

##### Wipe "artifacts/" from build node
```sh
ansible build -i ./inventory -a "rm -fr artifacts/"
```
##### Wipe chain, node key secrets, and validator keystore.
```sh
ansible all -i ./inventory -a "rm -fr chain/"
# Only wipe secrets to generate new session keys for validators and node key for boot nodes.
# ansible all -i ./inventory -a "bash -ic 'rm -fr secrets/ ; rm -fr keystore/'"
```

##### Kill  query-node from running rpc nodes.

```sh
ansible rpc -i ./inventory -a "bash -ic 'cd joystream/query-node ; yarn kill'"
# maybe checkout manual changes to .env file ?
# ansible rpc -i ./inventory -a "bash -ic 'cd joystream/ ; git checkout .'"
```

##### Apply latest security updates, reboot
```sh
ansible all -i ./inventory --become -a "bash -ic 'apt update; apt upgrade -y; reboot'"
```

##### Remove local artifacts of build and deployment from prior run
```sh
rm -fr ./chain
rm ./joystream-node
rm ./chain-spec-builder
rm ./session-keys
```

Howto run playbooks
```bash
ansible-playbook \
  -i /path/to/mainnet/inventory \
  --extra-vars "@/path/to/mainnet/config.yaml" \
  /path/to/joystream/devops/ansible/playbook-you-want-to-run.yml \
  --verbose
```

To deploy new chain, run playbooks in this order:

  - install-tools.yml
  - build-code.yml
  - fetch-binaries.yml
  - deploy-network.yml

genesis chainspec file should be found at `./chain/chanspec-raw.json`

#### Verify healthy network
- verify network in telemetry
- test all rpc nodes (rpc and query-node endpoints)
```sh
ansible rpc -i ./inventory -a "docker logs graphql-server --tail 5" -v
```
if you see the graphql-server containers logging ` [ 'Unauthorized access on /update-processor-state: 172.18.0.7' ]`
restart them:
```sh
ansible rpc -i ./inventory -a "docker restart graphql-server" -v
```
- test in poladot-js app
- backup keystores of validators (pgp) `~/keystore/`
- backup node keys of boot nodes. `~/secrets/node-key`

#### Configure Loadbalancers
 - Point rpc.joystream.org and query.joystream.org LBs to newly deployed rpc nodes
 
#### Faucet
- Configure and start faucet on first rpc node
- Update faucet section in `/etc/caddy/Caddyfile` for  `faucet.joystream.org`
- Update DNS faucet.joystream.org A record to point to first rpc node.
